#oc expose deployment spring-web-quickstart -n demo

kind: Service
apiVersion: v1
metadata:
  name: <deployment_name>
  labels:
    app: <deployment_name>
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: <deployment_name>
    deployment: <deployment_name>
